### ISSUE TITLE
no Go files

### ISSUE THREAD

**Issue by bannsec** [cuishark/cuishark#13]
Your install instructions do not work on a base ubuntu:18.04 docker image.

```
go get github.com/cuishark/cuishark
can't load package: package github.com/cuishark/cuishark: no Go files in /root/go/src/github.com/cuishark/cuishark
```

If i push through, i still get more errors

```
root@tester:~/go/src/github.com/cuishark/cuishark/cgocuishark# go install
# github.com/cuishark/cuishark/cgocuishark
./cgocuishark.go:13:10: fatal error: cuishark.h: No such file or directory
 #include <cuishark.h>
          ^~~~~~~~~~~~
compilation terminated.
```

Also, dependencies such as `libglib2.0-dev` should be mentioned.
